server:
  port: 8082

spring:
  profiles:
    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      min-idle: 5
      max-active: 20
      max-wait: 60000
      initial-size: 5
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
    filter: state,wall,log4j
    useGlobalDataSourceStat: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  redis:
    timeout: 300000
    port: 6379
    jedis:
      pool:
        max-wait: -1
        max-active: 20
        max-idle: 5
        min-idle: 0
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
mybatis:
  typeAliasesPackage: xyz.zhangbohan.applet.**.entity
  mapper-locations: classpath:mapping/*Mapper.xml
log4j:
  logger:
    java:
      sql:
        PreparedStatement: info
        Statement: info
        Connection: info